name: alpha_vantage_package
description: alpha vantage package api to get Stock Quotes.
version: 1.0.0
author: Basil Zuberi<basilzuberi@gmail.com>
homepage: https://www.github.com/basilzuberi/alpha_vantage_package

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

  test: ^1.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
